package types

type LoginReq struct {
	Username string
	Password string
}

type LoginResp struct {
	Code int
	Data LoginRespData
}

type LoginRespData struct {
	IsAdmin bool
	UserId  int
	Token   string
}

type SetupReq struct {
	Consensus string
	PeerPorts []Peerport

	OrdererPorts []Ordererport

	AutoGeneratedCerts bool
}

type Peerport struct {
	Main      int
	Chaincode int
}

type Ordererport struct {
	Main int
}
