aa: custom ec2 value
b:
    mike:
        name: 1
    lee:
        name: 2
c:
  - 111
  - 222
CrossDomain: false
routers:
  - from: orderer1:7050
    to: 127.0.0.1:30001
  - from: orderer2:7050
    to: 127.0.0.1:30002
# 示例看的风景
# this is test
bbb: # unsorted
    name: "kjf"
ccc:
    name: "mike"
    address:
