package models

type SetupRequest struct {
	// 网络名称
	NetworkName string `json:"networkName"`
	// 共识模式
	Consensus string `json:"consensus"`
	// 组织名称
	OrgName string `json:"orgName"`
	// 组织别名
	OrgAlias string `json:"orgAlias"`
	// peer 端口
	PeerPorts []PeerPorts `json:"peerPorts"`
	// orderer 端口
	OrdererPorts []OrdererPorts `json:"ordererPorts"`
	// 公司名称
	Company string `json:"company"`
	// 证书是否自动生成 现在只支持true
	AutoGeneratedCerts bool `json:"autoGeneratedCerts"`
}


type PeerPorts struct {
	Main      uint32 `json:"main"`
	Chaincode uint32 `json:"chaincode"`
}

type OrdererPorts struct {
	Main  uint32 `json:"main"`
	Debug uint32 `json:"debug"`
}


type IndirectInvokeRequest struct {
	Userid       string
	Org          string //直参机构的org
	ChannelName  string
	CcName       string
	Args         []string
	//PeerNodes    []*ServiceNode
	//OrdererNodes []*ServiceNode
}

type InitChannelRequest struct {
	Orgs        []string
	ChannelName string
	Peers       []string
}